name: UHC
version: 1.1
main: com.solemanseb.uhc.PluginMain
api-version: 1.16
commands:
  start:
    description: Start the Battledome game.
    usage: /start
    permission: uhc.start
  end:
    description: Stops the Battledome game.
    usage: /end
    permission: uhc.end
  team:
    description: Team commands
    usage: /team <args>
    permission: uhc.team
  speed:
    description: Increase the amount of blocks the border gets decreased by
    usage: /speed <number>
    permission: uhc.speed